
const state = {
    koreawomanList: [
        { 'name': '강소라', 'ext': 'gif' },
        { 'name': '강지영', 'ext': 'gif' },
        { 'name': '강한나', 'ext': 'gif' },
        { 'name': '경수진', 'ext': 'gif' },
        { 'name': '고보결', 'ext': 'gif' },
        { 'name': '고성희', 'ext': 'gif' },
        { 'name': '고아라', 'ext': 'gif' },
        { 'name': '고준희', 'ext': 'gif' },
        { 'name': '공효진', 'ext': 'gif' },
        { 'name': '권나라', 'ext': 'gif' },
        { 'name': '김고은', 'ext': 'gif' },
        { 'name': '김다미', 'ext': 'gif' },
        { 'name': '김사랑', 'ext': 'gif' },
        { 'name': '김세정', 'ext': 'gif' },
        { 'name': '김소은', 'ext': 'gif' },
        { 'name': '김소현', 'ext': 'gif' },
        { 'name': '김옥빈', 'ext': 'gif' },
        { 'name': '김유정', 'ext': 'gif' },
        { 'name': '김지원', 'ext': 'gif' },
        { 'name': '김지은', 'ext': 'gif' },
        { 'name': '김태리', 'ext': 'gif' },
        { 'name': '김혜수', 'ext': 'gif' },
        { 'name': '김희선', 'ext': 'gif' },
        { 'name': '나나', 'ext': 'gif' },
        { 'name': '나은', 'ext': 'gif' },
        { 'name': '노정의', 'ext': 'gif' },
        { 'name': '류혜영', 'ext': 'gif' },
        { 'name': '문가영', 'ext': 'gif' },
        { 'name': '문근영', 'ext': 'gif' },
        { 'name': '미연', 'ext': 'gif' },
        { 'name': '박규영', 'ext': 'gif' },
        { 'name': '박민영', 'ext': 'gif' },
        { 'name': '박보영', 'ext': 'gif' },
        { 'name': '박세영', 'ext': 'gif' },
        { 'name': '박소담', 'ext': 'gif' },
        { 'name': '박신혜', 'ext': 'gif' },
        { 'name': '박은빈', 'ext': 'gif' },
        { 'name': '박주현', 'ext': 'gif' },
        { 'name': '박지현', 'ext': 'gif' },
        { 'name': '박하선', 'ext': 'gif' },
        { 'name': '박혜수', 'ext': 'gif' },
        { 'name': '방민아', 'ext': 'gif' },
        { 'name': '배두나', 'ext': 'gif' },
        { 'name': '보나', 'ext': 'gif' },
        { 'name': '서예지', 'ext': 'gif' },
        { 'name': '서은수', 'ext': 'gif' },
        { 'name': '서지혜', 'ext': 'gif' },
        { 'name': '서현', 'ext': 'gif' },
        { 'name': '서현진', 'ext': 'gif' },
        { 'name': '설인아', 'ext': 'gif' },
        { 'name': '설현', 'ext': 'gif' },
        { 'name': '소진', 'ext': 'gif' },
        { 'name': '손나은', 'ext': 'gif' },
        { 'name': '송지효', 'ext': 'gif' },
        { 'name': '송햐윤', 'ext': 'gif' },
        { 'name': '송혜교', 'ext': 'gif' },
        { 'name': '수지', 'ext': 'gif' },
        { 'name': '신민아', 'ext': 'gif' },
        { 'name': '신세경', 'ext': 'gif' },
        { 'name': '신세휘', 'ext': 'gif' },
        { 'name': '신시아', 'ext': 'gif' },
        { 'name': '신예은', 'ext': 'gif' },
        { 'name': '신현빈', 'ext': 'gif' },
        { 'name': '신혜선', 'ext': 'gif' },
        { 'name': '아이유', 'ext': 'gif' },
        { 'name': '안소희', 'ext': 'gif' },
        { 'name': '앨리스 소희', 'ext': 'gif' },
        { 'name': '오연서', 'ext': 'gif' },
        { 'name': '원진아', 'ext': 'gif' },
        { 'name': '유리', 'ext': 'gif' },
        { 'name': '유이', 'ext': 'gif' },
        { 'name': '유인나', 'ext': 'gif' },
        { 'name': '유인영', 'ext': 'gif' },
        { 'name': '윤아', 'ext': 'gif' },
        { 'name': '이나영', 'ext': 'gif' },
        { 'name': '이다희', 'ext': 'gif' },
        { 'name': '이민정', 'ext': 'gif' },
        { 'name': '이보영', 'ext': 'gif' },
        { 'name': '이선빈', 'ext': 'gif' },
        { 'name': '이성경', 'ext': 'gif' },
        { 'name': '이세영', 'ext': 'gif' },
        { 'name': '이연희', 'ext': 'gif' },
        { 'name': '이영애', 'ext': 'gif' },
        { 'name': '이유비', 'ext': 'gif' },
        { 'name': '이주명', 'ext': 'gif' },
        { 'name': '이주빈', 'ext': 'gif' },
        { 'name': '이지아', 'ext': 'gif' },
        { 'name': '이채영', 'ext': 'gif' },
        { 'name': '이하나', 'ext': 'gif' },
        { 'name': '이하늬', 'ext': 'gif' },
        { 'name': '임수향', 'ext': 'gif' },
        { 'name': '임지연', 'ext': 'gif' },
        { 'name': '장나라', 'ext': 'gif' },
        { 'name': '전도연', 'ext': 'gif' },
        { 'name': '전소민', 'ext': 'gif' },
        { 'name': '전여빈', 'ext': 'gif' },
        { 'name': '전효성', 'ext': 'gif' },
        { 'name': '정려원', 'ext': 'gif' },
        { 'name': '정소민', 'ext': 'gif' },
        { 'name': '정수정', 'ext': 'gif' },
        { 'name': '정유미', 'ext': 'gif' },
        { 'name': '정은지', 'ext': 'gif' },
        { 'name': '정채연', 'ext': 'gif' },
        { 'name': '정호연', 'ext': 'gif' },
        { 'name': '제니', 'ext': 'gif' },
        { 'name': '조보아', 'ext': 'gif' },
        { 'name': '조유리', 'ext': 'gif' },
        { 'name': '조이', 'ext': 'gif' },
        { 'name': '조이현', 'ext': 'gif' },
        { 'name': '지수', 'ext': 'gif' },
        { 'name': '진기주', 'ext': 'gif' },
        { 'name': '채수빈', 'ext': 'gif' },
        { 'name': '채정안', 'ext': 'gif' },
        { 'name': '천우희', 'ext': 'gif' },
        { 'name': '최수영', 'ext': 'gif' },
        { 'name': '하니', 'ext': 'gif' },
        { 'name': '하연수', 'ext': 'gif' },
        { 'name': '하지원', 'ext': 'gif' },
        { 'name': '한가인', 'ext': 'gif' },
        { 'name': '한선화', 'ext': 'gif' },
        { 'name': '한소희', 'ext': 'gif' },
        { 'name': '한승연', 'ext': 'gif' },
        { 'name': '한예슬', 'ext': 'gif' },
        { 'name': '한지민', 'ext': 'gif' },
        { 'name': '한지현', 'ext': 'gif' },
        { 'name': '한채영', 'ext': 'gif' },
        { 'name': '한효주', 'ext': 'gif' },
        { 'name': '혜연', 'ext': 'gif' }
    ]
}

const getters = {
    koreawomanList: state => state.koreawomanList,
}

const mutations = {

}

const actions = {

}

export default {
    state,
    getters,
    mutations,
    actions
}